
name: CI (Jira cloud example with GH action, report results to Test Plan - demo)
on:
  workflow_dispatch:
    inputs:
      test_plan_key:
        description: 'Test Plan issue key'
        required: false
        default: ''
 
jobs:
  build:

    runs-on: Windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
